# NUMPY

In [ ]:
import numpy as np

## 1 - Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [ ]:
# Fonction qui génère un tableau d'entiers avec np.arange()
def tableau_entiers_intervalle(start, stop):
    # np.arange() crée un tableau allant de start à stop-1
    tableau = np.arange(start, stop)
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_entiers = tableau_entiers_intervalle(1, 11)
print("Tableau d'entiers de 1 à 10 :", tableau_entiers)

Tableau d'entiers de 1 à 10 : [ 1  2  3  4  5  6  7  8  9 10]


## 2 - Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [ ]:
# Fonction qui génère un tableau de nombres flottants aléatoires entre 0 et 1
def tableau_flottants_aleatoires(n):
    # np.random.rand() génère n flottants dans [0,1)
    tableau = np.random.rand(n)
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_flottants = tableau_flottants_aleatoires(5)
print("Tableau de nombres flottants aléatoires :", tableau_flottants)

Tableau de nombres flottants aléatoires : [0.13810387 0.46939255 0.91231391 0.43188204 0.16937058]


## 3 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [ ]:
# Fonction qui calcule la somme de tous les éléments d'un tableau NumPy
def somme_tableau(tableau):
    # np.sum() calcule la somme de tous les éléments du tableau
    resultat = np.sum(tableau)
    # Retourne le résultat
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5])
somme = somme_tableau(tableau_exemple)
print("Tableau :", tableau_exemple)
print("Somme :", somme)

Tableau : [1 2 3 4 5]
Somme : 15


## 4 - Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [ ]:
# Fonction qui calcule le produit scalaire de deux tableaux NumPy
def produit_scalaire(tableau_A, tableau_B):
    # Vérifie que les deux tableaux ont la même taille
    if tableau_A.shape != tableau_B.shape:
        raise ValueError("Les deux tableaux doivent avoir la même dimension pour calculer le produit scalaire.")
    # np.dot() calcule le produit scalaire
    resultat = np.dot(tableau_A, tableau_B)
    # Retourne le résultat
    return resultat

# Exemple d'utilisation
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
produit = produit_scalaire(A, B)
print("Tableau A :", A)
print("Tableau B :", B)
print("Produit scalaire de A et B :", produit)

Tableau A : [1 2 3]
Tableau B : [4 5 6]
Produit scalaire de A et B : 32


## 5 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [ ]:
# Fonction qui retourne les éléments uniques d'un tableau NumPy
def elements_uniques(tableau):
    # np.unique() retourne les éléments uniques du tableau
    resultat = np.unique(tableau)
    # Retourne le tableau des éléments uniques
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([4, 2, 2, 8, 4, 6, 5])
tableau_uniques = elements_uniques(tableau_exemple)
print("Tableau d'origine :", tableau_exemple)
print("Tableau des éléments uniques :", tableau_uniques)

Tableau d'origine : [4 2 2 8 4 6 5]
Tableau des éléments uniques : [2 4 5 6 8]


## 6 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [ ]:
# Fonction qui trie un tableau NumPy par ordre croissant
def trier_tableau(tableau):
    # np.sort() trie les éléments du tableau
    resultat = np.sort(tableau)
    # Retourne le tableau trié
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([5, 2, 9, 1, 5])
tableau_trie = trier_tableau(tableau_exemple)
print("Tableau d'origine :", tableau_exemple)
print("Tableau trié :", tableau_trie)

Tableau d'origine : [5 2 9 1 5]
Tableau trié : [1 2 5 5 9]


## 7 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [ ]:
# Fonction qui calcule les principales statistiques d'un tableau NumPy
def statistiques_tableau(tableau):
    # np.mean() calcule la moyenne
    moyenne = np.mean(tableau)
    # np.median() calcule la médiane
    mediane = np.median(tableau)
    # np.std() calcule l'écart-type
    ecart_type = np.std(tableau)
    # Retourne les trois statistiques sous forme de tuple
    return moyenne, mediane, ecart_type

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5, 6, 7])
moy, med, std = statistiques_tableau(tableau_exemple)
print("Tableau :", tableau_exemple)
print("Moyenne :", moy)
print("Médiane :", med)
print("Écart-type :", std)

Tableau : [1 2 3 4 5 6 7]
Moyenne : 4.0
Médiane : 4.0
Écart-type : 2.0


## 8 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [ ]:
# Fonction qui binarise un tableau NumPy selon une valeur seuil
def binariser_tableau(tableau, seuil):
    # np.zeros_like() crée un tableau de zéros de la même forme que le tableau d'entrée
    resultat = np.zeros_like(tableau)
    # Remplace par 1 les éléments >= seuil
    resultat[tableau >= seuil] = 1
    # Retourne le tableau binarisé
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([2, 5, 7, 3, 9, 0])
tableau_binaire = binariser_tableau(tableau_exemple, seuil=5)
print("Tableau d'origine :", tableau_exemple)
print("Tableau binaire  :", tableau_binaire)

Tableau d'origine : [2 5 7 3 9 0]
Tableau binaire  : [0 1 1 0 1 0]


## 9 - Créez une fonction qui prend un tableau NumPy de nombres entiers en entrée et renvoie un nouveau tableau contenant uniquement les nombres premiers du tableau d'origine.

In [ ]:
# Fonction qui retourne les nombres premiers d'un tableau NumPy
def nombres_premiers_tableau(tableau):
    # np.array() crée un tableau à partir d’une liste
    tableau_premiers = np.array([
        n for n in tableau 
        if n > 1 and all(n % i != 0 for i in range(2, n))
    ])
    # Retourne le tableau des nombres premiers
    return tableau_premiers

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tableau_premiers = nombres_premiers_tableau(tableau_exemple)
print("Tableau d'origine :", tableau_exemple)
print("Tableau des nombres premiers :", tableau_premiers)

Tableau d'origine : [ 1  2  3  4  5  6  7  8  9 10]
Tableau des nombres premiers : [2 3 5 7]


## 10 - Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [ ]:
import numpy as np

# Fonction qui crée un tableau Numpy 2D de taille (lignes x colonnes) avec des entiers aléatoires
def tableau_2D_aleatoire(lignes, colonnes, min_val, max_val):
    # np.random.randint() génère des entiers aléatoires entre min_val et max_val+1
    tableau = np.random.randint(min_val, max_val + 1, size=(lignes, colonnes))
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_exemple = tableau_2D_aleatoire(lignes=3, colonnes=3, min_val=1, max_val=10)
print("Tableau 2D aléatoire 3x3 (valeurs entre 1 et 10) :")
print(tableau_exemple)

Tableau 2D aléatoire 3x3 (valeurs entre 1 et 10) :
[[ 7 10  7]
 [ 5  2  4]
 [10  5  7]]
