# NUMPY

In [34]:
# On importe la bibliothèque NumPy et on lui donne l'alias 'np' pour simplifier les appels
import numpy as np

## 1 - Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [35]:
# Fonction qui génère un tableau d'entiers avec np.arange()
def tableau_entiers_intervalle(start, stop):
    # np.arange(start, stop) crée un tableau allant de start à stop-1
    tableau = np.arange(start, stop)
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_entiers = tableau_entiers_intervalle(1, 11)
print("Tableau d'entiers de 1 à 10 :", tableau_entiers)

Tableau d'entiers de 1 à 10 : [ 1  2  3  4  5  6  7  8  9 10]


## 2 - Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [36]:
# Fonction qui génère un tableau de nombres flottants aléatoires entre 0 et 1
def tableau_flottants_aleatoires(n):
    # np.random.rand(n) génère n flottants dans [0,1)
    tableau = np.random.rand(n)
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_flottants = tableau_flottants_aleatoires(5)
print("Tableau de nombres flottants aléatoires :", tableau_flottants)

Tableau de nombres flottants aléatoires : [0.00706255 0.12655939 0.88073616 0.72328642 0.73319602]


## 3 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [37]:
# Fonction qui calcule la somme de tous les éléments d'un tableau NumPy
def somme_tableau(tableau):
    # np.sum() calcule la somme de tous les éléments du tableau
    resultat = np.sum(tableau)
    # Retourne le résultat
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5])
somme = somme_tableau(tableau_exemple)
print("Tableau :", tableau_exemple)
print("Somme :", somme)

Tableau : [1 2 3 4 5]
Somme : 15


## 4 - Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [38]:
# Fonction qui calcule le produit scalaire de deux tableaux NumPy
def produit_scalaire(tableau_A, tableau_B):
    # Vérifie que les deux tableaux ont la même taille
    if tableau_A.shape != tableau_B.shape:
        raise ValueError("Les deux tableaux doivent avoir la même dimension pour calculer le produit scalaire.")
    # np.dot() calcule le produit scalaire
    resultat = np.dot(tableau_A, tableau_B)
    # Retourne le résultat
    return resultat

# Exemple d'utilisation
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
produit = produit_scalaire(A, B)
print("Tableau A :", A)
print("Tableau B :", B)
print("Produit scalaire de A et B :", produit)

Tableau A : [1 2 3]
Tableau B : [4 5 6]
Produit scalaire de A et B : 32


## 5 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [39]:
# Fonction qui retourne les éléments uniques d'un tableau NumPy
def elements_uniques(tableau):
    # np.unique() retourne les éléments uniques du tableau
    resultat = np.unique(tableau)
    # Retourne le tableau des éléments uniques
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([4, 2, 2, 8, 4, 6, 5])
tableau_uniques = elements_uniques(tableau_exemple)
print("Tableau d'origine :", tableau_exemple)
print("Tableau des éléments uniques :", tableau_uniques)

Tableau d'origine : [4 2 2 8 4 6 5]
Tableau des éléments uniques : [2 4 5 6 8]


## 6 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [40]:
# Fonction qui trie un tableau NumPy par ordre croissant
def trier_tableau(tableau):
    # np.sort() renvoie une copie triée du tableau, sans modifier l'original
    resultat = np.sort(tableau)
    # Retourne le tableau trié
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([5, 2, 9, 1, 5])
tableau_trie = trier_tableau(tableau_exemple)
print("Tableau d'origine :", tableau_exemple)
print("Tableau trié :", tableau_trie)

Tableau d'origine : [5 2 9 1 5]
Tableau trié : [1 2 5 5 9]


## 7 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [41]:
# Fonction qui calcule les principales statistiques d'un tableau NumPy
def statistiques_tableau(tableau):
    # np.mean() calcule la moyenne
    moyenne = np.mean(tableau)
    # np.median() calcule la médiane
    mediane = np.median(tableau)
    # np.std() calcule l'écart-type
    ecart_type = np.std(tableau)
    # Retourne les trois statistiques sous forme de tuple
    return moyenne, mediane, ecart_type

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5, 6, 7])
moy, med, std = statistiques_tableau(tableau_exemple)
print("Tableau :", tableau_exemple)
print("Moyenne :", moy)
print("Médiane :", med)
print("Écart-type :", std)

Tableau : [1 2 3 4 5 6 7]
Moyenne : 4.0
Médiane : 4.0
Écart-type : 2.0


## 8 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [42]:
def binariser_tableau(tableau):
    # Crée une copie du tableau pour ne pas modifier l'original
    resultat = np.copy(tableau)
    # Remplace les éléments < 5 par 0
    resultat[resultat < 5] = 0
    # Remplace les éléments >= 5 par 1
    resultat[resultat >= 5] = 1
    # Retourne le tableau binarisé
    return resultat

# Exemple d'utilisation
tableau_exemple = np.array([2, 5, 7, 3, 9, 0])
tableau_binaire = binariser_tableau(tableau_exemple)
print("Tableau original :", tableau_exemple)
print("Tableau binaire  :", tableau_binaire)

Tableau original : [2 5 7 3 9 0]
Tableau binaire  : [0 1 1 0 1 0]


## 9 - Créez une fonction qui prend un tableau NumPy de nombres entiers en entrée et renvoie un nouveau tableau contenant uniquement les nombres premiers du tableau d'origine.

In [43]:
# Fonction qui vérifie si un nombre est premier
def nombre_premier(n):
    if n <= 1:
        return False  # 0 et 1 ne sont pas premiers
    for i in range(2, n):
        if n % i == 0:
            return False  # divisible par un nombre autre que 1 et lui-même
    return True  # nombre premier

# Exemple d'utilisation
tableau_exemple = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tableau_premier = np.array([x for x in tableau_exemple if nombre_premier(x)])
print("Tableau d'origine :", tableau_exemple)
print("Tableau des nombres premiers :", tableau_premier)

Tableau d'origine : [ 1  2  3  4  5  6  7  8  9 10]
Tableau des nombres premiers : [2 3 5 7]


## 10 - Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [44]:
import numpy as np

# Fonction qui crée un tableau 2D de taille (lignes x colonnes) avec des entiers aléatoires
def tableau_2D_aleatoire(lignes=3, colonnes=3, min_val=1, max_val=10):
    # np.random.randint génère des entiers aléatoires entre min_val et max_val+1
    tableau = np.random.randint(min_val, max_val + 1, size=(lignes, colonnes))
    # Retourne le tableau généré
    return tableau

# Exemple d'utilisation
tableau_exemple = tableau_2D_aleatoire()
print("Tableau 2D aléatoire 3x3 :")
print(tableau_exemple)

# Exemple avec taille et intervalle personnalisé
tableau_personnalise = tableau_2D_aleatoire(lignes=4, colonnes=5, min_val=5, max_val=15)
print("\nTableau 2D aléatoire 4x5 (5 à 15) :")
print(tableau_personnalise)


Tableau 2D aléatoire 3x3 :
[[3 4 7]
 [5 2 8]
 [2 2 3]]

Tableau 2D aléatoire 4x5 (5 à 15) :
[[ 5 15 12 11  8]
 [ 9 15  8 12 12]
 [12  9  9  6 15]
 [ 7  5  5  7  8]]
